// .c
// Jokémon Entry Point
// by Kyle Furey

#include <jmon/jmon.h>

#pragma bank 0

/** Music used for testing. */
const audio_track_t test_song = {
	AUDIO_START,

	AUDIO_NOTE(NT_5_E, NT_4_B, NT_3_E, NS_C, TICK_BPM(320)),
	AUDIO_NOTE(NT_5_G, NT_CONTINUE, NT_3_E, NS_STOP, TICK_BPM(320)),
	AUDIO_NOTE(NT_5_A, NT_4_C, NT_3_A, NS_D, TICK_BPM(320)),
	AUDIO_NOTE(NT_5_B, NT_CONTINUE, NT_3_A, NS_STOP, TICK_BPM(320)),

	AUDIO_NOTE(NT_6_E, NT_5_B, NT_3_E, NS_C, TICK_BPM(320)),
	AUDIO_NOTE(NT_6_D, NT_CONTINUE, NT_3_E, NS_STOP, TICK_BPM(320)),
	AUDIO_NOTE(NT_6_C, NT_5_A, NT_3_A, NS_D, TICK_BPM(320)),
	AUDIO_NOTE(NT_5_B, NT_CONTINUE, NT_3_A, NS_STOP, TICK_BPM(320)),

	AUDIO_NOTE(NT_5_A, NT_5_E, NT_3_C, NS_C, TICK_BPM(320)),
	AUDIO_NOTE(NT_5_G, NT_CONTINUE, NT_3_C, NS_STOP, TICK_BPM(320)),
	AUDIO_NOTE(NT_5_E, NT_4_B, NT_3_G, NS_D, TICK_BPM(320)),
	AUDIO_NOTE(NT_5_D, NT_CONTINUE, NT_3_G, NS_STOP, TICK_BPM(320)),

	AUDIO_NOTE(NT_5_E, NT_4_C, NT_3_A, NS_C, TICK_BPM(320)),
	AUDIO_NOTE(NT_5_G, NT_CONTINUE, NT_3_A, NS_STOP, TICK_BPM(320)),
	AUDIO_NOTE(NT_5_A, NT_4_E, NT_3_E, NS_D, TICK_BPM(320)),
	AUDIO_NOTE(NT_6_C, NT_CONTINUE, NT_3_E, NS_STOP, TICK_BPM(320)),

	AUDIO_NOTE(NT_6_D, NT_5_G, NT_3_D, NS_C, TICK_BPM(320)),
	AUDIO_NOTE(NT_6_C, NT_CONTINUE, NT_3_D, NS_STOP, TICK_BPM(320)),
	AUDIO_NOTE(NT_5_B, NT_5_E, NT_3_B, NS_D, TICK_BPM(320)),
	AUDIO_NOTE(NT_5_A, NT_CONTINUE, NT_3_B, NS_STOP, TICK_BPM(320)),

	AUDIO_NOTE(NT_5_G, NT_5_D, NT_3_G, NS_C, TICK_BPM(320)),
	AUDIO_NOTE(NT_5_A, NT_CONTINUE, NT_3_G, NS_STOP, TICK_BPM(320)),
	AUDIO_NOTE(NT_5_B, NT_5_E, NT_3_B, NS_D, TICK_BPM(320)),
	AUDIO_NOTE(NT_6_D, NT_CONTINUE, NT_3_B, NS_STOP, TICK_BPM(320)),

	AUDIO_NOTE(NT_6_E, NT_5_B, NT_3_E, NS_C, TICK_BPM(320)),
	AUDIO_NOTE(NT_6_C, NT_CONTINUE, NT_3_E, NS_STOP, TICK_BPM(320)),
	AUDIO_NOTE(NT_5_B, NT_5_G, NT_3_G, NS_D, TICK_BPM(320)),
	AUDIO_NOTE(NT_5_G, NT_CONTINUE, NT_3_G, NS_STOP, TICK_BPM(320)),

	AUDIO_NOTE(NT_5_E, NT_4_B, NT_3_E, NS_C, TICK_BPM(320)),
	AUDIO_NOTE(NT_5_D, NT_CONTINUE, NT_3_E, NS_STOP, TICK_BPM(320)),
	AUDIO_NOTE(NT_5_E, NT_4_B, NT_3_E, NS_D, TICK_BPM(320)),
	AUDIO_NOTE(NT_STOP, NT_STOP, NT_STOP, NS_STOP, TICK_BPM(320)),

	AUDIO_END
};

/** Game loop. */
void main(void) NONBANKED {
	jmon_init();
	input_t input = { {0} };
	audio_t audio = { {0} };
	jmon_play_music(&audio, test_song, 0);
	while (true) {
		jmon_update_input(&input);
		jmon_update_audio(&audio);
		jmon_next_frame();
	}
}
