// .c
// Jokémon Read-only Audio
// by Kyle Furey

#include <jmon/jmon.h>

#pragma bank 0

/** Each precomputed note value. */
BANKREF(notes)

/** Precomputed note values for the pulse audio channel. */
const ushort_t rom_notes_pulse[NT_COUNT] = {
	[NT_2_C]=TODO,[NT_2_CS]=TODO,[NT_2_D]=TODO,[NT_2_DS]=TODO,[NT_2_E]=TODO,[NT_2_F]=TODO,[NT_2_FS]=TODO,[NT_2_G]=TODO,[NT_2_GS]=TODO,[NT_2_A]=TODO,[NT_2_AS]=TODO,[NT_2_B]=TODO,
	[NT_3_C]=TODO,[NT_3_CS]=TODO,[NT_3_D]=TODO,[NT_3_DS]=TODO,[NT_3_E]=TODO,[NT_3_F]=TODO,[NT_3_FS]=TODO,[NT_3_G]=TODO,[NT_3_GS]=TODO,[NT_3_A]=TODO,[NT_3_AS]=TODO,[NT_3_B]=TODO,
	[NT_4_C]=TODO,[NT_4_CS]=TODO,[NT_4_D]=TODO,[NT_4_DS]=TODO,[NT_4_E]=TODO,[NT_4_F]=TODO,[NT_4_FS]=TODO,[NT_4_G]=TODO,[NT_4_GS]=TODO,[NT_4_A]=TODO,[NT_4_AS]=TODO,[NT_4_B]=TODO,
	[NT_5_C]=TODO,[NT_5_CS]=TODO,[NT_5_D]=TODO,[NT_5_DS]=TODO,[NT_5_E]=TODO,[NT_5_F]=TODO,[NT_5_FS]=TODO,[NT_5_G]=TODO,[NT_5_GS]=TODO,[NT_5_A]=TODO,[NT_5_AS]=TODO,[NT_5_B]=TODO,
	[NT_6_C]=TODO,[NT_6_CS]=TODO,[NT_6_D]=TODO,[NT_6_DS]=TODO,[NT_6_E]=TODO,[NT_6_F]=TODO,[NT_6_FS]=TODO,[NT_6_G]=TODO,[NT_6_GS]=TODO,[NT_6_A]=TODO,[NT_6_AS]=TODO,[NT_6_B]=TODO,
	[NT_7_C]=TODO,[NT_7_CS]=TODO,[NT_7_D]=TODO,[NT_7_DS]=TODO,[NT_7_E]=TODO,[NT_7_F]=TODO,[NT_7_FS]=TODO,[NT_7_G]=TODO,[NT_7_GS]=TODO,[NT_7_A]=TODO,[NT_7_AS]=TODO,[NT_7_B]=TODO,
	[NT_8_C]=TODO,[NT_8_CS]=TODO,[NT_8_D]=TODO,[NT_8_DS]=TODO,[NT_8_E]=TODO,[NT_8_F]=TODO,[NT_8_FS]=TODO,[NT_8_G]=TODO,[NT_8_GS]=TODO,[NT_8_A]=TODO,[NT_8_AS]=TODO,[NT_8_B]=TODO,
};

/** Precomputed note values for the wave audio channel. */
const ushort_t rom_notes_wave[NT_COUNT] = {
	[NT_2_C]=TODO,[NT_2_CS]=TODO,[NT_2_D]=TODO,[NT_2_DS]=TODO,[NT_2_E]=TODO,[NT_2_F]=TODO,[NT_2_FS]=TODO,[NT_2_G]=TODO,[NT_2_GS]=TODO,[NT_2_A]=TODO,[NT_2_AS]=TODO,[NT_2_B]=TODO,
	[NT_3_C]=TODO,[NT_3_CS]=TODO,[NT_3_D]=TODO,[NT_3_DS]=TODO,[NT_3_E]=TODO,[NT_3_F]=TODO,[NT_3_FS]=TODO,[NT_3_G]=TODO,[NT_3_GS]=TODO,[NT_3_A]=TODO,[NT_3_AS]=TODO,[NT_3_B]=TODO,
	[NT_4_C]=TODO,[NT_4_CS]=TODO,[NT_4_D]=TODO,[NT_4_DS]=TODO,[NT_4_E]=TODO,[NT_4_F]=TODO,[NT_4_FS]=TODO,[NT_4_G]=TODO,[NT_4_GS]=TODO,[NT_4_A]=TODO,[NT_4_AS]=TODO,[NT_4_B]=TODO,
	[NT_5_C]=TODO,[NT_5_CS]=TODO,[NT_5_D]=TODO,[NT_5_DS]=TODO,[NT_5_E]=TODO,[NT_5_F]=TODO,[NT_5_FS]=TODO,[NT_5_G]=TODO,[NT_5_GS]=TODO,[NT_5_A]=TODO,[NT_5_AS]=TODO,[NT_5_B]=TODO,
	[NT_6_C]=TODO,[NT_6_CS]=TODO,[NT_6_D]=TODO,[NT_6_DS]=TODO,[NT_6_E]=TODO,[NT_6_F]=TODO,[NT_6_FS]=TODO,[NT_6_G]=TODO,[NT_6_GS]=TODO,[NT_6_A]=TODO,[NT_6_AS]=TODO,[NT_6_B]=TODO,
	[NT_7_C]=TODO,[NT_7_CS]=TODO,[NT_7_D]=TODO,[NT_7_DS]=TODO,[NT_7_E]=TODO,[NT_7_F]=TODO,[NT_7_FS]=TODO,[NT_7_G]=TODO,[NT_7_GS]=TODO,[NT_7_A]=TODO,[NT_7_AS]=TODO,[NT_7_B]=TODO,
	[NT_8_C]=TODO,[NT_8_CS]=TODO,[NT_8_D]=TODO,[NT_8_DS]=TODO,[NT_8_E]=TODO,[NT_8_F]=TODO,[NT_8_FS]=TODO,[NT_8_G]=TODO,[NT_8_GS]=TODO,[NT_8_A]=TODO,[NT_8_AS]=TODO,[NT_8_B]=TODO,
};

/** Precomputed note values for the noise audio channel. */
const ushort_t rom_notes_noise[NT_COUNT] = {
	[NT_2_C]=TODO,[NT_2_CS]=TODO,[NT_2_D]=TODO,[NT_2_DS]=TODO,[NT_2_E]=TODO,[NT_2_F]=TODO,[NT_2_FS]=TODO,[NT_2_G]=TODO,[NT_2_GS]=TODO,[NT_2_A]=TODO,[NT_2_AS]=TODO,[NT_2_B]=TODO,
	[NT_3_C]=TODO,[NT_3_CS]=TODO,[NT_3_D]=TODO,[NT_3_DS]=TODO,[NT_3_E]=TODO,[NT_3_F]=TODO,[NT_3_FS]=TODO,[NT_3_G]=TODO,[NT_3_GS]=TODO,[NT_3_A]=TODO,[NT_3_AS]=TODO,[NT_3_B]=TODO,
	[NT_4_C]=TODO,[NT_4_CS]=TODO,[NT_4_D]=TODO,[NT_4_DS]=TODO,[NT_4_E]=TODO,[NT_4_F]=TODO,[NT_4_FS]=TODO,[NT_4_G]=TODO,[NT_4_GS]=TODO,[NT_4_A]=TODO,[NT_4_AS]=TODO,[NT_4_B]=TODO,
	[NT_5_C]=TODO,[NT_5_CS]=TODO,[NT_5_D]=TODO,[NT_5_DS]=TODO,[NT_5_E]=TODO,[NT_5_F]=TODO,[NT_5_FS]=TODO,[NT_5_G]=TODO,[NT_5_GS]=TODO,[NT_5_A]=TODO,[NT_5_AS]=TODO,[NT_5_B]=TODO,
	[NT_6_C]=TODO,[NT_6_CS]=TODO,[NT_6_D]=TODO,[NT_6_DS]=TODO,[NT_6_E]=TODO,[NT_6_F]=TODO,[NT_6_FS]=TODO,[NT_6_G]=TODO,[NT_6_GS]=TODO,[NT_6_A]=TODO,[NT_6_AS]=TODO,[NT_6_B]=TODO,
	[NT_7_C]=TODO,[NT_7_CS]=TODO,[NT_7_D]=TODO,[NT_7_DS]=TODO,[NT_7_E]=TODO,[NT_7_F]=TODO,[NT_7_FS]=TODO,[NT_7_G]=TODO,[NT_7_GS]=TODO,[NT_7_A]=TODO,[NT_7_AS]=TODO,[NT_7_B]=TODO,
	[NT_8_C]=TODO,[NT_8_CS]=TODO,[NT_8_D]=TODO,[NT_8_DS]=TODO,[NT_8_E]=TODO,[NT_8_F]=TODO,[NT_8_FS]=TODO,[NT_8_G]=TODO,[NT_8_GS]=TODO,[NT_8_A]=TODO,[NT_8_AS]=TODO,[NT_8_B]=TODO,
};
